version: "3.4"

services:

  bifrosthub:
    build:
      context: .
      args:
        RELEASE_VERSION: 0.0.0-local
    ports:
      - "5134:5134"
    volumes:
      - ./src/Web.Application/appsettings.Docker.json:/app/appsettings.Docker.json
        
  mongo:
    image: mongo:6.0
    command: ["--replSet", "rs0", "--bind_ip_all", "--port", "27017"]
    ports:
      - "27017:27017"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    healthcheck:
      test: echo "try { rs.status() } catch (err) { rs.initiate({_id:'rs0',members:[{_id:0,host:'host.docker.internal:27017'}]}) }" | mongosh --port 27017 --quiet
      interval: 5s
      timeout: 30s
      start_period: 0s
      start_interval: 1s
      retries: 30
        
  seq:
    image: datalust/seq:latest
    environment:
      - ACCEPT_EULA=Y
    ports:
      - "5341:5341"
      - "8081:80"
    volumes:
      - seq_data:/data

volumes:
  seq_data: