version: "3.4"

services:

  bifrosthub:
    image: sparcopt/bifrosthub:0.0.1-beta.11
    ports:
      - "5134:5134"
    volumes:
      - ./src/Web.Application/appsettings.Docker.json:/app/appsettings.Docker.json
        
  mongo:
    image: mongo:6.0
    ports:
      - "27017:27017"
        
  seq:
    image: datalust/seq:latest
    environment:
      - ACCEPT_EULA=Y
    ports:
      - "5341:5341"
      - "8081:80"
    volumes:
      - seq_data:/data

volumes:
  seq_data: