version: "3.4"

services:

  bifrosthub:
    build:
      context: .
      args:
        RELEASE_VERSION: 0.0.0-local
    ports:
      - "5134:5134"
    environment:
      - OdinEye__ApiUrl=
      - Steam__ApiKey=
        
  seq:
    image: datalust/seq:latest
    environment:
      - ACCEPT_EULA=Y
    ports:
      - "5341:5341"
      - "8081:80"
    volumes:
      - seq_data:/data

volumes:
  seq_data: